// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using TC_IC_API1.Model;

[TestFixture]
public class TestBillingOrderPage
{
    private IWebDriver driver;
    public TestBillingOrderPage(IWebDriver driver)
    {
        this.driver = driver;
    }

  public void SubmitBillingOrder(BillingOrder Order) {
    driver.Navigate().GoToUrl("http://qaauto.co.nz/billing-order-form/");
    driver.Manage().Window.Size = new System.Drawing.Size(1366, 728);
   
    driver.FindElement(By.Id("wpforms-locked-24-field_form_locker_password")).Click();
    driver.FindElement(By.Id("wpforms-locked-24-field_form_locker_password")).SendKeys("Testing");
    driver.FindElement(By.Id("wpforms-locked-24-field_form_locker_password")).SendKeys(Keys.Enter);
    driver.FindElement(By.Id("wpforms-24-field_0")).SendKeys(Order.firstName);
    driver.FindElement(By.Id("wpforms-24-field_0-last")).SendKeys(Order.lastName);
    driver.FindElement(By.Id("wpforms-24-field_1")).SendKeys(Order.email);
    driver.FindElement(By.Id("wpforms-24-field_3")).SendKeys("abcd2");
    driver.FindElement(By.Id("wpforms-24-field_3-address2")).SendKeys("abcd3");
    driver.FindElement(By.Id("wpforms-24-field_3-city")).SendKeys("abcdc");
    {
      var dropdown = driver.FindElement(By.Id("wpforms-24-field_3-state"));
      dropdown.FindElement(By.XPath("//option[. = 'Alaska']")).Click();
    }
    driver.FindElement(By.Id("wpforms-24-field_3-postal")).SendKeys("70506");
    driver.FindElement(By.Id("wpforms-24-field_6")).SendKeys("xyz");
    driver.FindElement(By.CssSelector(".wpforms-form-page-wrap")).Click();
  //  Assert.That(driver.FindElement(By.CssSelector("#wpforms-confirmation-24 > p")).Text, Is.EqualTo("Thanks for contacting us! We will be in touch with you shortly."));
    {
      var element = driver.FindElement(By.CssSelector("#wpforms-confirmation-24 > p"));
            driver.FindElement(By.Id("wpforms-form-page-page")).Click();
      string value = element.GetAttribute("value");
      string locator = string.Format("option[@value='%s']", value);
      string selectedText = element.FindElement(By.XPath(locator)).Text;
    //  Assert.That(selectedText, Is.EqualTo("Thanks for contacting us! We will be in touch with you shortly."));
    }
  }
}
